### PR TITLE
Begin writing outline for tutorial

### PR DESCRIPTION
**Pull request by NeuroShepherd**

### CODE REVIEW

**Comment by NeuroShepherd** [comment]
Hey @FlorianPargent, I started a very simple outline file for the renv tutorial. Feel free to contribute or provide feedback if you have the time. After I have a completed outline, I'll start making separate `.qmd` files to split the content up into separate chapters/pages on this site.

**Comment by NeuroShepherd** [comment]
1. > most people (like me) will probably expect that renv tracks all packages that are installed in your project (which is not true!)

**Comment by NeuroShepherd** [comment]
@FlorianPargent some misc. questions:

> most people (like me) will probably expect that renv tracks all packages that are installed in your project (which is not true!)
Can you elaborate on the issue you encountered? I was already aware of this feature in {renv}, but I'm not sure what some of the common failure routes might be--I would write some notes on "Frequent Failure Reasons" or similar.

> renv::checkout(date = "01.01.2024") for users familier with groundhog or the old checkout package
I might mention that this is possible, but I don't know if I would want to include it in the tutorial because checking out specific dates might be getting too complicated for most users. They might not realize that this will downgrade/upgrade *all* package versions to what was available on the same date.

> I myself still have problems with that sometimes and have not found a good workflow
Can you elaborate on the issues you've encountered? The only {renv} problem I've ever had was when trying to deploy an application that needed a custom package from an enterprise version of GitLab, and I think this was ultimately a proxy issue. In other words, I have ([un]fortunately) no experience with failures to restore or activate renv.

> I am pretty sure this has changed recently, I have used renv for years now and have never heard about renv/settings.json until a few weeks ago
I think this was included around or at the 1.0 release last year. I agree on being explicit about needing to commit renv files though; I'm considering including the `renv::history()` function so that people can explicitly return to previous states of their lock file (without having to know how to revert their whole project to an earlier commit or cherry pick from earlier commits).

> We could add a short chapter on what additional things you have to know when you want to use renv + binder in a quarto project: https://quarto.org/docs/projects/binder.html
I would just link out to the binder webpage, or to a (future) OSC tutorial on setting up binder.

> Probably too niche for the tutorial but something I have wrestled with in my own projects: When you want to use renv together with packages from the Stan universe you must follow these steps: http://mc-stan.org/r-packages/#using-with-renv
I'd argue in favor of talking about how and why to set different repository options to use e.g. STAN, Posit Package Manager, and other repos. This would be more of a side note when explaining what repositories are, but useful nonetheless.

**Comment by FlorianPargent** [comment]
The example of a prominent function in the *psych* R package:  
Setting `rotate = "promax"` requires the *GPArotation* package which the package lists under "Suggests".
When using the renv defaults, the *GPArotation* package would not be tracked in the project.

```
library(psych)
fa(Holzinger, nfactors = 2, fm = "ml", rotate = "promax")
# Loading required namespace: GPArotation
# Failed with error:  ‘there is no package called ‘GPArotation’’
# Error in kaiser(loadings, rotate = "Promax", ...) : 
#   GPArotation is required for the Kaiser normalization
```

**Comment by NeuroShepherd** [comment]
> The example of a prominent function in the _psych_ R package: Setting `rotate = "promax"` requires the _GPArotation_ package which the package lists under "Suggests". When using the renv defaults, the _GPArotation_ package would not be tracked in the project, right?
> 
> ```
> library(psych)
> fa(Holzinger, nfactors = 2, fm = "ml", rotate = "promax")
> # Loading required namespace: GPArotation
> # Failed with error:  ‘there is no package called ‘GPArotation’’
> # Error in kaiser(loadings, rotate = "Promax", ...) : 
> #   GPArotation is required for the Kaiser normalization
> ```

Thanks for the example! This would presumably also be an issue when using {groundhogr}, assuming that its custom package installation follows the same defaults as `base::install.packages()`; for the `dependencies` argument: `The default, NA, means c("Depends", "Imports", "LinkingTo").` so suggested packages are not installed by default.

**Comment by NeuroShepherd** [comment]
Hey @FlorianPargent, do you happen to have another example like the one listed above with the {psych} and {GPArotation} packages? 

I was intending to include that as one of the Exercises for the renv tutorial, but it seems that {GPArotation} has been upgraded to an Import in the {psych} package so this "error" is only reproducible prior to v2.4.7.

**Pull request merged**
